// Code generated by "stringer -type=Overload"; DO NOT EDIT.

package main

import "fmt"

const _Overload_name = "OverVoltageProtectionOverCurrentProtectionOverPowerProtection"

var _Overload_index = [...]uint8{0, 21, 42, 61}

func (i Overload) String() string {
	i -= 1
	if i >= Overload(len(_Overload_index)-1) {
		return fmt.Sprintf("Overload(%d)", i+1)
	}
	return _Overload_name[_Overload_index[i]:_Overload_index[i+1]]
}
