// Code generated by "stringer -type=Protection"; DO NOT EDIT.

package main

import "fmt"

const _Protection_name = "NoneOverVoltageProtectionOverCurrentProtectionOverPowerProtection"

var _Protection_index = [...]uint8{0, 4, 25, 46, 65}

func (i Protection) String() string {
	if i >= Protection(len(_Protection_index)-1) {
		return fmt.Sprintf("Protection(%d)", i)
	}
	return _Protection_name[_Protection_index[i]:_Protection_index[i+1]]
}
